#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mar 24 2024

@author: sayakaminegishi
"""
#pip install pyabf
# pip install IPFX
import pyabf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib import gridspec
import scipy
from scipy import signal
from scipy.signal import find_peaks
from scipy.optimize import curve_fit


#load data
filepath = "/Users/sayakaminegishi/Documents/Birren Lab/Voltage clamp analysis/voltage clamp example data/2024_03_25_01_0000.abf"
abfdata = pyabf.ABF(filepath)
print(abfdata) #gtives info about abfdata, such as no. of sweeps, channels, duration

#show all sweeps' command data
plt.figure(figsize=(8, 5))
plt.title("all sweeps")
plt.ylabel(abfdata.sweepLabelC)
plt.xlabel(abfdata.sweepLabelX)
for i in abfdata.sweepList:
    abfdata.setSweep(i)
    plt.plot(abfdata.sweepX, abfdata.sweepC, alpha=.5, label="sweep %d" % (i))
plt.legend()
plt.show()


fig = plt.figure(figsize=(8, 5))

# plot recorded (ADC) waveform
plt.subplot(211)
plt.plot(abfdata.sweepX, abfdata.sweepY)
plt.xlabel(abfdata.sweepLabelX)
plt.ylabel(abfdata.sweepLabelY)

# plot command (DAC) waveform
plt.subplot(212)
plt.plot(abfdata.sweepX, abfdata.sweepC, 'r')
plt.xlabel(abfdata.sweepLabelX)
plt.ylabel(abfdata.sweepLabelC)

plt.tight_layout()
plt.show()

print(abfdata.sweepC)


# abfdata.setSweep(1)
# print("sweep data (ADC):", abfdata.sweepY)
# print("sweep command (DAC):", abfdata.sweepC)
# print("sweep times (seconds):", abfdata.sweepX)


# #plot of 14th sweep
# plt.plot(abfdata.sweepX, abfdata.sweepY)
# plt.xlabel(abfdata.sweepLabelX)
# plt.ylabel(abfdata.sweepLabelY)
# plt.show()

#show 1st, 6th, 11th and 16th sweep data
plt.figure(figsize=(8, 5))
plt.title("all sweeps")
plt.ylabel(abfdata.sweepLabelY)
plt.xlabel(abfdata.sweepLabelX)
for i in abfdata.sweepList:
    abfdata.setSweep(i)
    plt.plot(abfdata.sweepX, abfdata.sweepY, alpha=.5, label="sweep %d" % (i))
plt.legend()
plt.show()



#plot multi-channel ABFs

fig = plt.figure(figsize=(8, 5))

# plot the first channel
abfdata.setSweep(sweepNumber=0, channel=0)
plt.plot(abfdata.sweepX, abfdata.sweepY, label="Channel 1")

# plot the second channel
abfdata.setSweep(sweepNumber=0, channel=1)
plt.plot(abfdata.sweepX, abfdata.sweepY, label="Channel 2")

# decorate the plot
plt.ylabel(abfdata.sweepLabelY)
plt.xlabel(abfdata.sweepLabelX)
plt.axis([25, 45, -70, 50])
plt.legend()
plt.show()